services:
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000 --noreload"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    container_name: livraria-allbooks
    environment:
      - DJANGO_SETTINGS_MODULE=allbooks.settings
