# Generated by Django 5.0.1 on 2024-07-23 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='autor',
            name='telefone',
            field=models.BigIntegerField(blank=True),
        ),
    ]
