# Generated by Django 4.0.6 on 2022-07-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('editoras', '0001_initial'),
        ('autores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=50)),
                ('IBSN', models.BigIntegerField()),
                ('edicao', models.IntegerField()),
                ('data_de_impressao', models.DateField()),
                ('traducao', models.CharField(blank=True, max_length=100)),
                ('numero_de_paginas', models.IntegerField()),
                ('quantidade_em_estoque', models.IntegerField()),
                ('descricao', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9)),
                ('desconto', models.DecimalField(blank=True, decimal_places=2, max_digits=9)),
                ('imagem', models.ImageField(blank=True, upload_to='uploads')),
                ('autor', models.ManyToManyField(to='autores.autor')),
                ('editora', models.ManyToManyField(to='editoras.editora')),
            ],
        ),
    ]
