# Generated by Django 4.0.6 on 2022-07-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Editora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('CNPJ', models.BigIntegerField()),
                ('endereco', models.CharField(max_length=80)),
                ('cidade', models.CharField(max_length=45)),
                ('estado', models.CharField(max_length=45)),
                ('telefone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
