# Generated by Django 5.0.1 on 2024-07-23 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_compra_estado_compra_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='estado',
            field=models.CharField(choices=[('acre', 'Acre'), ('alagoas', 'Alagoas'), ('amapa', 'Amapá'), ('amazonas', 'Amazonas'), ('bahia', 'Bahia'), ('ceara', 'Ceará'), ('distrito_federal', 'Distrito Federal'), ('espirito_santos', 'Espírito Santo'), ('goais', 'Goiás'), ('maranhao', 'Maranhão'), ('mato_grosso', 'Mato Grosso'), ('mato_grosso_do_sul', 'Mato Grosso do Sul'), ('minas_gerais', 'Minas Gerais'), ('para', 'Pará'), ('paraiba', 'Paraíba'), ('parana', 'Paraná'), ('pernambuco', 'Pernambuco'), ('piaui', 'Piauí'), ('rio_de_janeiro', 'Rio de Janeiro'), ('rio_grande_do_norte', 'Rio Grande do Norte'), ('rio_grande_do_sul', 'Rio Grande do Sul'), ('rondonia', 'Rondônia'), ('roraima', 'Roraima'), ('santa_catarina', 'Santa Catarina'), ('sao_paulo', 'São Paulo'), ('sergipe', 'Sergipe'), ('tocantins', 'Tocantins')], default='Escolha...', max_length=100),
        ),
        migrations.AlterField(
            model_name='compra',
            name='pais',
            field=models.CharField(choices=[('brasil', 'Brasil')], default='Escolha...', max_length=100),
        ),
    ]
